
- name: download the mysql repo.
  get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: "{{deploy_user_dir}}"

- name: yum update
  yum: name=* state=latest
  become: true

- name: run rpm
  command: rpm -ivh mysql-community-release-el7-5.noarch.rpm
  become: true
  ignore_errors: yes

- name: install mysql server
  yum:
    name: mysql-server
  become: true

- name: make sure mysql is running.
  command: systemctl start mysqld
  become: true

- name: Install mysql-devel
  yum:
    name: mysql-devel
  become: true

- name: Instal MySql-Python
  yum:
    name: MySQL-python
  become: true

- name: Create transactions database
  mysql_db:
    name: transactions
    state: present
    login_user : root