- name: ensure epel is installed on the os.
  yum: 
    name: epel-release
    state: present
  become: true

- name: ensure pip is installed on the os.
  yum:
    name: python-pip
    state: present
  become: true

- name: ensure virtualenv is installed on the os.
  pip:
    name: virtualenv
  become: yes



DONT FORGET TO INSTALL THE EXTRA MYSQL PACKAGE WE NEED