
- name: update packages via yum.
  yum: name=* state=latest
  become: true

- name: install wget
  yum: 
   name: wget
   state: present
  become: true

- name: instal epel
  yum: 
    name: epel-release
    state: present
  become: true

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
  become: true

- name: install pip
  yum:
    name: python-pip
    state: present
  become: true

- name: install virtualenv
  pip:
    name: virtualenv
    state: present
  become: true

- name: install unzip
  yum:
    name: unzip
    state: present
  become: true 



