
- name: update packages via yum.
  yum: name=* state=latest
  become: true

- name: install wget
  yum: 
   name: wget
   state: present
  become: true

- name: ensure epel is installed on the os.
  yum: 
    name: epel-release
    state: present
  become: true

- name: ensure pip is installed on the os.
  yum:
    name: python-pip
    state: present
  become: true

- name: ensure virtualenv is installed on the os.
  pip:
    name: virtualenv
    state: present
  become: yes



